services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports: [4000:4000]
    environment: [JEKYLL_ENV=docker]

volumes:
  bundle: